### ISSUE TITLE
Support DPDK 16.1

### ISSUE THREAD

**Issue by mmanoj** [akiskourtis/sriov-dpdk#1]
Hi @akiskourtis 

Is this your app support DPDK 16.1 as I compare the code with vanilla DPDK L3forwarding code is different.

Please advice how can I compile with DPDK 16.1 

Thank you,
Manoj M

**Comment by akiskourtis** [comment]
Hello Manoj,

It should, I suppose, although you need to replace the dpdk folder with the newer version, and also the Makefile inside the examples folder to include nDPI support.

Let me know how this turns out.

**Comment by mmanoj** [comment]
Hi @akiskourtis 

Thanks for the quick feedback, I will change as requested and test. Will update you the result.

**Comment by mmanoj** [comment]
Hi @akiskourtis 

Is there specific reason you choose L3 forwarder,  I'm planning to test with skeleton forwarder as I manage to do basic traffic forwarding with it to internet and back to PC.

Please advice.

**Comment by akiskourtis** [comment]
Hello @mmanoj 

When I had started the development we only had L2 and L3 forwarders, so it was the only choice.
The basic forwarding should be fine!

Cheers

**Comment by mmanoj** [comment]
Hi @akiskourtis 

Thanks for the clarification, I will try the basic forwarding and update you the progress.

**Comment by mmanoj** [comment]
hi @akiskourtis 

This is for your update, I done basic integration with skeleton app and nDPI. Some fine tuning required. Once finalize I will send you pull request.

**Comment by akiskourtis** [comment]
Cool!
