### ISSUE TITLE
Traffic not forwarding after DPI

### ISSUE THREAD

**Issue by mmanoj** [akiskourtis/sriov-dpdk#2]
Hi,

I successfully integrate the basic forwarding app with nDPI. However traffic not forwarding to second port and back. Please advice how to share the code so we can joint test.

Thank you,
Manoj M

**Comment by akiskourtis** [comment]
Sorry for the delayed response, great news, you can do maybe a pull request?

Thanks

**Comment by akiskourtis** [comment]
Have you matched the dpdk ports to the physical ports correctly?

**Comment by mmanoj** [comment]
Hi,

Sorry, I manage to fix it, because I not define some function related to packet forward without inline static. after I define it it got work, currently I'm testing the detection and flow/bytes counts. 

Next step to make it multi core. I will update the progress/help required. Once finish I will share via github.
